
services:

  indicatorvirginbot:
    image: indicatorvirginbot
    container_name: indicatorvirginbot
    depends_on:
      - statekeeper
    env_file:
      - .env
      - indicatorvirginbot/.env
    ports:
      - 102:8080
      - 5102:5005 # debug agentlib
      - 9102:9102 # profiling jmx
      - 1089:1089
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./metrics/logs/indicatorvirginbot:/tmp/logs
    mem_limit: 512m

  macsawbot:
    image: macsawbot
    container_name: macsawbot
    depends_on:
      - statekeeper
    env_file:
      - .env
      - macsawbot/.env
    ports:
      - 103:8080
      - 5103:5005 # debug agentlib
      - 9103:9103 # profiling jmx
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./metrics/logs/macsawbot:/tmp/logs
    mem_limit: 512m

  bigasscandlesbot:
    image: bigasscandlesbot
    container_name: bigasscandlesbot
    depends_on:
      - statekeeper
    env_file:
      - .env
      - bigasscandlesbot/.env
    ports:
      - 104:8080
      - 5104:5005 # debug agentlib
      - 9104:9104 # profiling jmx
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./metrics/logs/bigasscandlesbot:/tmp/logs
    mem_limit: 512m

  statekeeper:
    image: statekeeper
    container_name: statekeeper
    depends_on:
      - redis_binance
      - postgres
    env_file:
      - .env
      - statekeeper/.env
    ports:
      - 100:8080
      - 5100:5005 # debug agentlib
      - 9100:9100 # profiling jmx
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./metrics/logs/statekeeper:/tmp/logs
    mem_limit: 512m

  redis_binance:
    image: redis:7.0.7-alpine
    container_name: redis_binance
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 6399:6379
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/redis:/data
    mem_limit: 64m
    mem_reservation: 32m

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgres:/var/lib/postgresql/data
    mem_limit: 256m
    mem_reservation: 128m

# https://habr.com/ru/post/578744/
#  postgres_exporter:
#    container_name: postgres_exporter
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    image: prometheuscommunity/postgres-exporter
#    env_file:
#      - binancespotbot_env.env
#    volumes:
#      - .metrics/postgres_exporter_queries.yaml:/etc/postgres_exporter/queries.yaml:ro
#    ports:
#      - "9181:9187"

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4
#    depends_on:
#      - postgres
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    env_file:
#      - .env
#    ports:
#      - 5050:80
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "statekeeper:host-gateway"
      - "indicatorvirginbot:host-gateway"
      - "macsawbot:host-gateway"
      - "bigasscandlesbot:host-gateway"
    ports:
      - 9096:9090
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./metrics/prometheus.yaml:/etc/prometheus.yaml
    mem_limit: 128m
    mem_reservation: 64m
    command: [
      "--config.file=/etc/prometheus.yaml" 
      # "--enable-feature=exemplar-storage",
      # "--storage.tsdb.path=/prometheus",
      # "--web.console.libraries=/usr/share/prometheus/console_libraries",
      # "--web.console.templates=/usr/share/prometheus/consoles",
      # "--web.enable-remote-write-receiver"
    ]

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - 3003:3000
    user: ':' # it needs to avoid error of permissions for volumes
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./metrics/grafana:/var/lib/grafana
      - ./metrics/grafana-dashboards:/etc/grafana/provisioning/dashboards
      - ./metrics/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    mem_limit: 128m
    mem_reservation: 64m


# --- archived

#  dailyvolumesbot:
#    image: dailyvolumesbot
#    container_name: dailyvolumesbot
#    depends_on:
#      - statekeeper
#    env_file:
#      - .env
#      - dailyvolumesbot/.env
#    ports:
#      - 101:8080
#      - 5101:5005 # debug agentlib
#      - 9101:9101 # profiling jmx
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#      - ./metrics/logs/dailyvolumesbot:/tmp/logs
#    mem_limit: 512m