logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:-INFO}
    web: ${LOGGING_LEVEL_WEB:-INFO}
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    path: /tmp/logs
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-history: 30

server:
  undertow:
    accesslog:
      enabled: true
      dir: "/tmp/logs"
      pattern: "common"
      suffix: ".log"
      prefix: "access_log"
#  tomcat:
#    accesslog:
#      enabled: true
#      rotate: false
#      suffix: ".log"
#      prefix: "access_log"
#      directory: "/tmp/logs"
#      pattern: "common"

spring:
  main:
    banner-mode: off
    lazy-initialization: true
  profiles:
    active: "default"
  output:
    ansi:
      enabled: ALWAYS
  # mvc:
  #     pathmatch:
  #         matching-strategy: ant-path-matcher

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

applicationconfig:
  testLaunch: ${TEST_LAUNCH}
  useTestnet: ${BINANCE_USE_TESTNET}
  useTestnetStreaming: ${BINANCE_USE_TESTNET_STREAMING}
  apiKey: ${BINANCE_API_KEY}
  secret: ${BINANCE_SECRET_KEY}
  stateKeeperURL: http://${STATEKEEPER_HOST}:${STATEKEEPER_PORT}

strategy:
  # ------------------ global
  global:
    tradingAsset: ${STRATEGY_GLOBAL_TRADING_ASSET}
    maximalPairPrice: ${STRATEGY_GLOBAL_MAXIMAL_PAIR_PRICE}
    minimalAssetBalance: ${STRATEGY_GLOBAL_MINIMAL_ASSET_BALANCE}
    baseOrderVolume: ${STRATEGY_GLOBAL_BASE_ORDER_VOLUME}
  volumeNimble:
    enabled: ${VOLUMENIMBLE_ENABLED}
    followBtcTrend: ${VOLUMENIMBLE_FOLLOW_BTC_TREND}
    ordersQtyLimit: ${VOLUMENIMBLE_ORDERS_QTY_LIMIT}
    averagingEnabled: ${VOLUMENIMBLE_AVERAGING_ENABLED}
    priceDecreaseFactor: ${VOLUMENIMBLE_PRICE_DECREASE_FACTOR}
    pairTakeProfitFactor: ${VOLUMENIMBLE_PAIR_TAKE_PROFIT_FACTOR}
    takeProfitPriceDecreaseFactor: ${VOLUMENIMBLE_TAKE_PROFIT_PRICE_DECREASE_FACTOR}
    averagingTrigger: ${VOLUMENIMBLE_AVERAGING_TRIGGER}
    workedOutSignalsIgnoringPeriod: ${VOLUMENIMBLE_WORKED_OUT_SIGNALS_IGNORING_PERIOD}
    monitoringExpirationTime: ${VOLUMENIMBLE_MONITORING_EXPIRATION_TIME}
    updateBtcTrend:
      initialDelay: ${VOLUMENIMBLE_UPDATE_BTC_TREND_INITIAL_DELAY}
      fixedDelay: ${VOLUMENIMBLE_UPDATE_BTC_TREND_FIXED_DELAY}
    startCandlstickEventsCacheUpdating:
      initialDelay: ${VOLUMENIMBLE_START_CANDLESTICKEVENTS_CACHE_UPDATING_INITIAL_DELAY}
      fixedDelay: ${VOLUMENIMBLE_START_CANDLESTICKEVENTS_CACHE_UPDATING_FIXED_DELAY}