#FROM resurfaceio/alpine-jdk17:3.17.0a
#FROM springci/graalvm-ce:java17-0.12.x
FROM ubuntu:kinetic

ADD ./build/native/nativeCompile/statekeeper statekeeper/

ENTRYPOINT ["/bin/sh", "-c", "./statekeeper/statekeeper"]