# metrics configured by this article:
# https://refactorfirst.com/spring-boot-prometheus-grafana

services:
  
#  binancespotbot:
#    image: binancespotbot
#    container_name: binancespotbot
#    env_file:
#      - binancespotbot_env.env
#    ports:
#      - 85:8080
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#      - ./src/main/resources/metrics/logs:/tmp/logs

  prometheus:
    image: prom/prometheus
    network_mode: host
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src/main/resources/metrics/prometheus.yaml:/etc/prometheus.yaml
    command: [
      "--config.file=/etc/prometheus.yaml" 
      # "--enable-feature=exemplar-storage",
      # "--storage.tsdb.path=/prometheus",
      # "--web.console.libraries=/usr/share/prometheus/console_libraries",
      # "--web.console.templates=/usr/share/prometheus/consoles",
      # "--web.enable-remote-write-receiver"
    ]

  grafana:
    image: grafana/grafana-oss
    network_mode: host
    container_name: grafana
    ports:
      - 3000:3000
    user: "$UID:$GID"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src/main/resources/metrics/grafana:/var/lib/grafana
       # # grafana.ini see: https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
       # - ./src/main/resources/metrics/grafana.ini:/etc/grafana/grafana.ini
       # # Pre-load the data sources
       # - ./src/main/resources/metrics/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
       # Pre-load the Hello Observability dashboard
#       - ./src/main/resources/metrics/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
#      - GF_PATHS_CONFIG=/usr/share/grafana/grafana.ini
#      - GF_PATHS_DATA=/usr/share/grafana
#      - GF_PATHS_HOME=/usr/share/grafana
#      - GF_PATHS_LOGS=/usr/share/grafana
#      - GF_PATHS_PLUGINS=/usr/share/grafana/plugins
#      - GF_PATHS_PROVISIONING=/usr/share/grafana/provisioning
       # - GF_FEATURE_TOGGLES_ENABLE=tempoSearch,tempoServiceGraph,tempoApmTable

  # loki:
  #   image: grafana/loki
  #   container_name: loki
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./src/main/resources/metrics/loki-config.yaml:/etc/config/loki.yaml
  #   entrypoint:
  #     - /usr/bin/loki
  #     - -config.file=/etc/config/loki.yaml
  #   ports:
  #     - 3100:3100

  # tempo:
  #   image: grafana/tempo:1.5.0
  #   container_name: tempo
  #   command: [ "-config.file=/etc/tempo.yaml" ]
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./src/main/resources/metrics/tempo-local.yaml:/etc/tempo.yaml
  #     - ./src/main/resources/metrics/tempo-data:/tmp/tempo
  #   ports:
  #     - "14268"  # jaeger ingest
  #     - "3200"   # tempo
  #     - "4317"  # otlp grpc
  #     - "4318"  # otlp http
  #     - "9411"   # zipkin

#   agent:
#     image: grafana/agent
#     container_name: agent
#     volumes:
#     - /etc/timezone:/etc/timezone:ro
#     - /etc/localtime:/etc/localtime:ro
#       # Agent configuration
#       - ./src/main/resources/metrics/agent.yaml:/etc/agent-config/agent.yaml
#       # Log files
#       - ./src/main/resources/metrics/logs/hello-observability.log:/tmp/hello-observability.log
#       - ./src/main/resources/metrics/logs/access_log.log:/tmp/access_log.log
#     entrypoint:
#       - /bin/agent
#       - -config.file=/etc/agent-config/agent.yaml
#       - -metrics.wal-directory=/tmp/agent/wal
#       - -enable-features=integrations-next
#       - -config.expand-env
#       - -config.enable-read-api
#     environment:
#       HOSTNAME: agent
# #      REMOTE_WRITE_HOST: cortex:9009
#       LOKI_HOST: loki:3100
#       TEMPO_HOST: tempo:3200
#     ports:
#       - "12345:12345"
#     depends_on:
#       - loki
#       - tempo

# Our load generator
  # load-generator:
  #   image: curlimages/curl:latest
  #   volumes:
  #     - ../hello-observability/load-generator.sh:/tmp/load-generator.sh
  #   command: /bin/sh -c "/tmp/load-generator.sh"
  
  # grafana:
  #   image: grafana/grafana:9.1.0
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     # grafana.ini
  #     # see: https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
  #     - ./src/main/resources/metrics/grafana.ini:/etc/grafana/grafana.ini
  #     # Pre-load the data sources
  #     - ./src/main/resources/metrics/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
  #     # Pre-load the Hello Observability dashboard
  #     - ./src/main/resources/metrics/dashboards:/etc/grafana/provisioning/dashboards
  #   environment:
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_AUTH_DISABLE_LOGIN_FORM=true
  #     - GF_USERS_DEFAULT_THEME=light
  #     - GF_FEATURE_TOGGLES_ENABLE=tempoSearch,tempoServiceGraph,tempoApmTable
  #   ports:
  #     - "3000:3000"