services:
  
  binancespotbot:
    image: binancespotbot:latest
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin